HOSTS:
  centos-65-x64:
    roles:
      - agent
    platform: el-6-x86_64
    box : puppetlabs/centos-6.6-64-nocm
    hypervisor : vagrant
  ubuntu-server-1204-x64:
    roles:
      - agent
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    hypervisor: vagrant
  ubuntu-server-1404-x64:
    roles:
      - master
      - agent
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
